@extends('layouts.community', ['title' => 'Content request'])

@section('content')
    <div class="mb-7"><p class="text-xs font-semibold uppercase tracking-[.18em] text-[#ff7693]">Publisher and rights-holder support</p><h1 class="mt-2 text-3xl font-semibold tracking-[-.04em]">Request an action</h1><p class="mt-2 max-w-2xl text-sm leading-6 text-zinc-500">Ask us to remove or correct an item, exclude a domain from discovery, or review another rights concern. This creates a durable request for the maintainers.</p></div>
    <form method="POST" action="{{ route('legal.content-request.store') }}" class="loom-card grid gap-6 p-6 sm:grid-cols-2 sm:p-8">@csrf
        <div><label class="form-label" for="type">Request</label><select class="form-input" id="type" name="type"><option value="remove">Remove content</option><option value="correct">Correct content</option><option value="opt_out">Exclude a domain</option><option value="rights">Other rights concern</option></select>@error('type')<p class="form-error">{{ $message }}</p>@enderror</div>
        <div><label class="form-label" for="content_url">Affected URL</label><input class="form-input" id="content_url" type="url" name="content_url" value="{{ old('content_url') }}" required placeholder="https://…" />@error('content_url')<p class="form-error">{{ $message }}</p>@enderror</div>
        <div><label class="form-label" for="requester_name">Your name</label><input class="form-input" id="requester_name" name="requester_name" value="{{ old('requester_name') }}" required />@error('requester_name')<p class="form-error">{{ $message }}</p>@enderror</div>
        <div><label class="form-label" for="requester_email">Your email</label><input class="form-input" id="requester_email" type="email" name="requester_email" value="{{ old('requester_email') }}" required />@error('requester_email')<p class="form-error">{{ $message }}</p>@enderror</div>
        <div class="sm:col-span-2"><label class="form-label" for="relationship">Relationship to the content</label><input class="form-input" id="relationship" name="relationship" value="{{ old('relationship') }}" required placeholder="Author, publisher, rights holder, subject…" />@error('relationship')<p class="form-error">{{ $message }}</p>@enderror</div>
        <div class="sm:col-span-2"><label class="form-label" for="details">Details</label><textarea class="form-input min-h-40" id="details" name="details" required maxlength="3000" placeholder="Tell us what should change and why.">{{ old('details') }}</textarea>@error('details')<p class="form-error">{{ $message }}</p>@enderror</div>
        <div class="flex items-center justify-between gap-4 border-t border-white/8 pt-6 sm:col-span-2"><p class="text-xs leading-5 text-zinc-600">We use these details only to assess and respond to this request. See <a href="{{ route('legal.privacy') }}" class="text-zinc-400">privacy</a>.</p><button class="loom-button shrink-0">Submit request</button></div>
    </form>
@endsection
