@extends('layouts.community', ['title' => 'Content principles'])

@section('content')
    <article class="loom-card p-6 sm:p-9"><p class="text-xs font-semibold uppercase tracking-[.18em] text-[#e73562] dark:text-[#ff7693]">Trust by design</p><h1 class="mt-3 text-3xl font-semibold tracking-[-.04em]">Content principles</h1><p class="mt-4 text-lg leading-7 text-zinc-600 dark:text-zinc-400">Laraloom should create attention for Laravel creators—not extract value from them.</p>
        <div class="mt-9 space-y-8 text-sm leading-7 text-zinc-600 dark:text-zinc-400">
            <section><h2 class="text-base font-semibold text-zinc-900 dark:text-zinc-200">We index, summarise, and send people back</h2><p class="mt-2">Automated discovery stores a title, canonical URL, publisher attribution, publication time, tags, and a short original summary. We do not store or republish article bodies, paywalled material, newsletter archives, or media assets. Every discovered item links to its original source.</p></section>
            <section><h2 class="text-base font-semibold text-zinc-900 dark:text-zinc-200">Approved access only</h2><p class="mt-2">Sources are allow-listed. We prefer publisher RSS feeds and documented APIs, honour robots exclusion rules and rate limits, and identify our requests where the protocol permits. X content is displayed only through X's official API or oEmbed—not scraped from pages. Tavily is configured for metadata-only discovery with raw page content disabled.</p></section>
            <section><h2 class="text-base font-semibold text-zinc-900 dark:text-zinc-200">AI is an editor, never the source</h2><p class="mt-2">Azure OpenAI evaluates relevance and writes a short synthesis from returned metadata. AI-curated items are visibly labelled and include their source. Low-confidence or unattributed items are not published.</p></section>
            <section><h2 class="text-base font-semibold text-zinc-900 dark:text-zinc-200">Community posts</h2><p class="mt-2">Members must publish their own writing or short commentary with a link and attribution. Do not paste work you do not own, impersonate others, spam, harass, or publish private information. Maintainers may remove content that violates these rules.</p></section>
            <section><h2 class="text-base font-semibold text-zinc-900 dark:text-zinc-200">Opt out, correction, and takedown</h2><p class="mt-2">Anyone can report illegal content or non-consensual intimate imagery without an account. Publishers and rights holders can request removal, correction, or exclusion of their domain. Use the <a class="font-medium text-[#e73562] dark:text-[#ff7693]" href="{{ route('legal.content-request') }}">rights and safety form</a> with a precise reference, your relationship to the content, and the requested action.</p></section>
        </div>
        <p class="mt-9 border-t border-zinc-200 pt-5 text-xs text-zinc-500 dark:border-white/8 dark:text-zinc-600">Last updated {{ now()->format('j F Y') }}. This policy describes Laraloom's product rules and is not legal advice.</p>
    </article>
@endsection
